TEXTS = {
    "ru": {
        "welcome": "Добро пожаловать в VPN-магазин.\nВыберите действие:",
        "main_info": "Пользователь: {name}\nПодписка: {subscription}",
        "no_subscription": "нет",
        "balance": "Ваш баланс: {balance} RUB",
        "subscription_none": "У вас пока нет активной подписки.",
        "language_changed": "Язык переключен на русский.",
        "tariffs_title": "Доступные тарифы:",
        "support_menu": "Раздел поддержки:",
        "enter_subject": "Введите тему тикета:",
        "enter_ticket_text": "Введите текст обращения:",
        "ticket_created": "Тикет #{ticket_id} создан. Ответ придет сюда.",
        "tickets_empty": "У вас пока нет тикетов.",
        "buy_success": "Подписка успешно оформлена.",
        "insufficient_balance": "Недостаточно средств на балансе.",
        "connect_missing": "Ссылка подключения пока недоступна, обратитесь в поддержку.",
        "ticket_reply_saved": "Ответ сохранён.",
        "admin_only": "Команда доступна только администраторам.",
        "admin_menu": "Админ-меню:",
    },
    "en": {
        "welcome": "Welcome to the VPN shop.\nChoose an action:",
        "main_info": "User: {name}\nSubscription: {subscription}",
        "no_subscription": "none",
        "balance": "Your balance: {balance} RUB",
        "subscription_none": "You have no active subscription yet.",
        "language_changed": "Language switched to English.",
        "tariffs_title": "Available plans:",
        "support_menu": "Support menu:",
        "enter_subject": "Enter ticket subject:",
        "enter_ticket_text": "Enter ticket message:",
        "ticket_created": "Ticket #{ticket_id} created. We will reply here.",
        "tickets_empty": "You do not have tickets yet.",
        "buy_success": "Subscription was purchased successfully.",
        "insufficient_balance": "Insufficient balance.",
        "connect_missing": "Connect URL is unavailable. Contact support.",
        "ticket_reply_saved": "Reply saved.",
        "admin_only": "This command is for admins only.",
        "admin_menu": "Admin menu:",
    },
}

